stages:
  - init
  - build
  - deploy

npm-install:
  stage: init
  script:
    - npm install
  cache:
    - key: build-files
      paths:
        - node_modules/*

npm-build:
  stage: build
  script:
    - npm run build
  cache:
    - key: build-files
      paths:
        - node_modules/*
  artifacts:
    paths:
      - build/*
    expire_in: 30 minutes

deploy-s3:
  stage: deploy
  script:
    - aws s3 cp build/ s3://idea-boards-frontend/ --recursive
